import { z } from "zod";

export const intentClassificationOutputSchema = z.object({
  intent: z
    .enum([
      "search_property",
      "summarize_finance"
    ])
    .describe("The intent of the user query"),
  confidence: z
    .number()
    .int()
    .min(0)
    .max(100)
    .describe("The confidence score of the intent generated by the model"),
});
